### ISSUE TITLE
FDC ID should be integer

### ISSUE THREAD

**Issue by oscarsiles** [TandoorRecipes/open-tandoor-data#12]
Since updating to the latest version of Tandoor (1.5.10), I can no longer download updates as it tries to import some fdc_id values which are strings (e.g. `170931-ground` or `2345232-cherry`). From my cursory look at the migrations in the latest Tandoor version, this has been changed to an IntegerField.

The schema appears to have not been updated to reflect this.
https://github.com/TandoorRecipes/open-tandoor-data/blob/8cdaedbb3f0c9452ff817fe9fc372887a87db23d/schema.json#L17

**Comment by langerdennis** [comment]
Same issue here, set up a fresh instance of Tandoor with the open-date-plugin and get the same error message in the logs:

`ValueError: Field 'fdc_id' expected a number but got '170931-ground'`

**Comment by Blackclaws** [comment]
Just ran into the same issue. Is upgrading an instance to 1.5.10 a solution as a workaround?

**Comment by Szeraax** [comment]
Just wait for the next release and hosted update and it'll all be good. Vabene is traveling for work and will back soon to fix this up.
