### ISSUE TITLE
How do users make use of this data?

### ISSUE THREAD

**Issue by GiantFrog** [TandoorRecipes/open-tandoor-data#9]
Sorry, I feel like an idiot, I'm super appreciative of you doing all this base work, but have no idea how to bring it in to my tandoor instance! All documentation is focused on contribution, I can't find anything mentioning actually using it in the docs here, the docs for tandoor itself, or the import section of my tandoor installation that I just updated to 1.5.4.

I'd like to ask for some help and some more clear instruction for everyone else who comes along in the future. I can write documentation myself if I learn the secrets.

**Comment by GiantFrog** [comment]
Well I found it! A reddit comment somewhere mentioned a space management page. Top right -> Space Settings, url /space-manage/1 for me, there's a button for open data import right there in the UI. Don't muck around importing the json from this project as a json recipe, it's not in the units or foods sections either, it's there. Hope this comment helps just one other person someday, that'd make me happy.

**Comment by GwinGit** [comment]
Hey, I'm now in the same boat of feeling stupid. I'm on the space management page and found the open data section. But there is only a disclaimer about the open data import being in beta and no actual import button.

![Screenshot](https://github.com/user-attachments/assets/b058cb7d-9338-4686-ba38-a2c503a40568)

So how do I now go about importing the data?
